spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-trial-master-db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: product-trial-master

server:
  port: 8080
jwt:
  secret: MyVerySecureAndLongSecretKey12345
  expiration: 3600000
admin:
  mail: admin@admin.com
security:
  public-endpoints:
    - /api/account
    - /api/token
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html


